// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFkRaWyU_j6qcspXuOsJUXteRDIw8thqE',
    appId: '1:237515794933:web:3bf3da8a398ac5de0258bc',
    messagingSenderId: '237515794933',
    projectId: 'the-alisto',
    authDomain: 'the-alisto.firebaseapp.com',
    storageBucket: 'the-alisto.firebasestorage.app',
    measurementId: 'G-FJLJ1C6GZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvIoxyj8z2RT2_sBa2pzo4hYh48jwcBdk',
    appId: '1:237515794933:android:ea7d395f777103000258bc',
    messagingSenderId: '237515794933',
    projectId: 'the-alisto',
    storageBucket: 'the-alisto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUqpC2d3DjmBTWGG0PYwHjmNQe3DWS964',
    appId: '1:237515794933:ios:c19df825ef2568f20258bc',
    messagingSenderId: '237515794933',
    projectId: 'the-alisto',
    storageBucket: 'the-alisto.firebasestorage.app',
    iosBundleId: 'com.example.alistoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUqpC2d3DjmBTWGG0PYwHjmNQe3DWS964',
    appId: '1:237515794933:ios:c19df825ef2568f20258bc',
    messagingSenderId: '237515794933',
    projectId: 'the-alisto',
    storageBucket: 'the-alisto.firebasestorage.app',
    iosBundleId: 'com.example.alistoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFkRaWyU_j6qcspXuOsJUXteRDIw8thqE',
    appId: '1:237515794933:web:49fdb5998f3107ff0258bc',
    messagingSenderId: '237515794933',
    projectId: 'the-alisto',
    authDomain: 'the-alisto.firebaseapp.com',
    storageBucket: 'the-alisto.firebasestorage.app',
    measurementId: 'G-VZ24ZD229P',
  );
}
